services:
  backend:
    build: ./backend
    container_name: my-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: sh -c "npm run seed && npm run dev"

  client:
    build: ./client
    container_name: my-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: